In [ ]:
!pip install kaggle
from google.colab import files
files.upload()

Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (1.7.4.5)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle) (6.3.0)
Requirement already satisfied: certifi>=14.05.14 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2026.2.25)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.12/dist-packages (from kaggle) (3.4.4)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from kaggle) (3.11)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle) (5.29.6)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: setuptools>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from kaggle) (75.2.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.17.0)
Requirement already satisfied: text-unidecode in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from kaggle) (0.5.1)

Saving kaggle.json to kaggle.json

{'kaggle.json': b'{"username":"kumarblast","key":"53781a89a5d89e2d49b15171bc98097f"}'}

In [ ]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [ ]:
!kaggle datasets download -d javagarm/movies-on-ott-platforms

Dataset URL: https://www.kaggle.com/datasets/javagarm/movies-on-ott-platforms
License(s): CC0-1.0
Downloading movies-on-ott-platforms.zip to /content
  0% 0.00/579k [00:00<?, ?B/s]
100% 579k/579k [00:00<00:00, 984MB/s]

In [ ]:
!unzip movies-on-ott-platforms.zip

Archive:  movies-on-ott-platforms.zip
  inflating: MoviesOnStreamingPlatforms_updated.csv

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv("MoviesOnStreamingPlatforms_updated.csv")

In [ ]:
df.head(45)

,ID,Title,Year,Age,IMDb,Rotten Tomatoes,Netflix,Hulu,Prime Video,Disney+,Type,Directors,Genres,Country,Language,Runtime
0,1,Inception,2010,13+,8.8,87%,1.00,0,0,0,0,Christopher Nolan,"Action,Adventure,Sci-Fi,Thriller","United States,United Kingdom","English,Japanese,French",148.0
1,2,The Matrix,1999,18+,8.7,87%,1.00,0,0,0,0,"Lana Wachowski,Lilly Wachowski","Action,Sci-Fi",United States,English,136.0
2,3,Avengers: Infinity War,2018,13+,8.5,84%,1.00,0,0,0,0,"Anthony Russo,Joe Russo","Action,Adventure,Sci-Fi",United States,English,149.0
3,4,Back to the Future,1985,7+,8.5,96%,1.00,0,0,0,0,Robert Zemeckis,"Adventure,Comedy,Sci-Fi",United States,English,116.0
4,5,"The Good, the Bad and the Ugly",1966,18+,8.8,97%,1.00,0,1,0,0,Sergio Leone,Western,"Italy,Spain,West Germany",Italian,161.0
5,6,Spider-Man: Into the Spider-Verse,2018,7+,8.4,97%,1.00,0,0,0,0,"Bob Persichetti,Peter Ramsey,Rodney Rothman","Animation,Action,Adventure,Family,Sci-Fi",United States,"English,Spanish",117.0
6,7,The Pianist,2002,18+,8.5,95%,1.00,0,1,0,0,Roman Polanski,"Biography,Drama,Music,War","United Kingdom,France,Poland,Germany","English,German,Russian",150.0
7,8,Django Unchained,2012,18+,8.4,87%,1.00,0,0,0,0,Quentin Tarantino,"Drama,Western",United States,"English,German,French,Italian",165.0
8,9,Raiders of the Lost Ark,1981,7+,8.4,95%,1.00,0,0,0,0,Steven Spielberg,"Action,Adventure",United States,"English,German,Hebrew,Spanish,Arabic,Nepali",115.0
9,10,Inglourious Basterds,2009,18+,8.3,89%,1.00,0,0,0,0,Quentin Tarantino,"Adventure,Drama,War","Germany,United States","English,German,French,Italian",153.0
10,11,Taxi Driver,1976,18+,8.3,95%,1.00,0,0,0,0,Martin Scorsese,"Crime,Drama",United States,"English,Spanish",114.0
11,12,3 Idiots,2009,13+,8.4,100%,1.01,0,1,0,0,Rajkumar Hirani,"Comedy,Drama",India,"Hindi,English",170.0
12,13,Pan's Labyrinth,2006,18+,8.2,95%,1.00,0,0,0,0,Guillermo del Toro,"Drama,Fantasy,War","Mexico,Spain",Spanish,118.0
13,14,Room,2015,18+,8.1,93%,1.00,0,0,0,0,Lenny Abrahamson,"Drama,Thriller","Ireland,Canada,United Kingdom,United States",English,118.0
14,15,Monty Python and the Holy Grail,1975,7+,8.2,97%,1.00,0,0,0,0,"Terry Gilliam,Terry Jones","Adventure,Comedy,Fantasy",United Kingdom,"English,French,Latin",91.0
15,16,Once Upon a Time in the West,1968,13+,8.5,95%,1.00,0,1,0,0,Sergio Leone,Western,"Italy,United States","Italian,English,Spanish",165.0
16,17,Indiana Jones and the Last Crusade,1989,13+,8.2,88%,1.00,0,0,0,0,Steven Spielberg,"Action,Adventure",United States,"English,German,Greek,Arabic",127.0
17,18,Groundhog Day,1993,7+,8.0,96%,1.00,0,0,0,0,Harold Ramis,"Comedy,Fantasy,Romance",United States,"English,French,Italian",101.0
18,19,The King's Speech,2010,18+,8.0,95%,1.00,0,0,0,0,Tom Hooper,"Biography,Drama,History","United Kingdom,United States,Australia",English,118.0
19,20,Her,2013,18+,8.0,95%,1.00,0,0,0,0,Spike Jonze,"Drama,Romance,Sci-Fi",United States,English,126.0
20,21,There Will Be Blood,2007,18+,8.2,91%,1.00,0,0,0,0,Paul Thomas Anderson,Drama,United States,"English,American Sign Language",158.0
21,22,The Social Network,2010,13+,7.7,96%,1.00,0,0,0,0,David Fincher,"Biography,Drama",United States,"English,French",120.0
22,23,Dallas Buyers Club,2013,18+,8.0,93%,1.00,0,0,0,0,Jean-Marc Vallée,"Biography,Drama",United States,"English,Japanese",117.0
23,24,The Perks of Being a Wallflower,2012,13+,8.0,86%,1.00,0,0,0,0,Stephen Chbosky,"Drama,Romance",United States,English,103.0
24,25,Life of Brian,1979,18+,8.1,95%,1.00,0,0,0,0,Terry Jones,Comedy,United Kingdom,"English,Latin",94.0
25,26,Ex Machina,2015,18+,7.7,92%,1.00,0,0,0,0,Alex Garland,"Drama,Mystery,Sci-Fi,Thriller","United Kingdom,United States",English,108.0
26,27,Silver Linings Playbook,2012,18+,7.7,92%,1.00,0,0,0,0,David O. Russell,"Comedy,Drama,Romance",United States,English,122.0
27,28,District 9,2009,18+,7.9,90%,1.00,0,0,0,0,Neill Blomkamp,"Action,Sci-Fi,Thriller","South Africa,United States,New Zealand,Canada","English,Nyanja,Afrikaans,Zulu,Xhosa,Southern S...",112.0
28,29,The Irishman,2019,18+,7.9,96%,1.00,0,0,0,0,Martin Scorsese,"Biography,Crime,Drama",United States,"English,Italian,Latin,Spanish,German",209.0
29,30,Moon,2009,18+,7.9,90%,1.00,0,0,0,0,Duncan Jones,"Drama,Mystery,Sci-Fi","United Kingdom,United States","English,Spanish",97.0
30,31,Marriage Story,2019,18+,8.0,95%,1.00,0,0,0,0,Noah Baumbach,"Comedy,Drama,Romance","United Kingdom,United States","English,Spanish",137.0
31,32,Drive,2011,18+,7.8,92%,1.00,0,1,0,0,Nicolas Winding Refn,"Crime,Drama",United States,"English,Spanish",100.0
32,33,Train to Busan,2016,NaN,7.5,94%,1.00,0,1,0,0,Sang-ho Yeon,"Action,Horror,Thriller",South Korea,"Korean,Hawaiian",118.0
33,34,Incredibles 2,2018,7+,7.6,94%,1.00,0,0,0,0,Brad Bird,"Animation,Action,Adventure,Comedy,Family,Sci-Fi",United States,English,118.0
34,35,Dangal,2016,7+,8.4,88%,1.00,0,0,0,0,Nitesh Tiwari,"Action,Biography,Drama,Sport",India,Hindi,161.0
35,36,Klaus,2019,7+,8.2,94%,1.00,0,0,0,0,"Sergio Pablos,Carlos Martínez López","Animation,Adventure,Comedy,Family",Spain,"English,Saami",96.0
36,37,Minority Report,2002,13+,7.6,90%,1.00,0,0,0,0,Steven Spielberg,"Action,Crime,Mystery,Sci-Fi,Thriller",United States,"English,Swedish",145.0
37,38,Mystic River,2003,18+,7.9,88%,1.00,0,0,0,0,Clint Eastwood,"Crime,Drama,Mystery,Thriller","United States,Australia",English,138.0
38,39,Like Stars on Earth,2007,7+,8.4,91%,1.00,0,0,0,0,"Aamir Khan,Amole Gupte","Drama,Family",India,"Hindi,English",165.0
39,40,Ferris Bueller's Day Off,1986,13+,7.8,80%,1.00,0,0,0,0,John Hughes,Comedy,United States,"English,German",103.0
40,41,Despicable Me,2010,7+,7.6,81%,1.00,0,0,0,0,"Pierre Coffin,Chris Renaud","Animation,Comedy,Family,Fantasy","United States,France",English,95.0
41,42,Hell or High Water,2016,18+,7.6,97%,1.00,0,0,0,0,David Mackenzie,"Action,Crime,Drama,Thriller,Western",United States,English,102.0
42,43,Sin City,2005,18+,8.0,77%,1.00,0,0,0,0,"Frank Miller,Robert Rodriguez,Quentin Tarantino","Crime,Thriller",United States,English,124.0
43,44,Ip Man,2008,18+,8.0,85%,1.00,0,0,0,0,Wilson Yip,"Action,Adventure,Biography,Drama,History","Hong Kong,China","Cantonese,Mandarin,Japanese",106.0
44,45,Indiana Jones and the Temple of Doom,1984,7+,7.6,85%,1.00,0,0,0,0,Steven Spielberg,"Action,Adventure",United States,"English,Sinhalese,Hindi",118.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16744 entries, 0 to 16743
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               16744 non-null  int64
 1   Title            16744 non-null  object
 2   Year             16744 non-null  int64
 3   Age              7354 non-null   object
 4   IMDb             16173 non-null  float64
 5   Rotten Tomatoes  5158 non-null   object
 6   Netflix          16744 non-null  float64
 7   Hulu             16744 non-null  int64
 8   Prime Video      16744 non-null  int64
 9   Disney+          16744 non-null  int64
 10  Type             16744 non-null  int64
 11  Directors        16018 non-null  object
 12  Genres           16469 non-null  object
 13  Country          16309 non-null  object
 14  Language         16130 non-null  object
 15  Runtime          16152 non-null  float64
dtypes: float64(3), int64(6), object(7)
memory usage: 2.0+ MB

In [ ]:
df.isnull().sum()

ID                     0
Title                  0
Year                   0
Age                 9390
IMDb                 571
Rotten Tomatoes    11586
Netflix                0
Hulu                   0
Prime Video            0
Disney+                0
Type                   0
Directors            726
Genres               275
Country              435
Language             614
Runtime              592
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df = df.drop_duplicates()

In [ ]:
num_cols = df.select_dtypes(include=['int64','float64']).columns
cat_cols = df.select_dtypes(include=['object']).columns

print("Numerical Columns:", num_cols)
print("Categorical Columns:", cat_cols)

Numerical Columns: Index(['ID', 'Year', 'IMDb', 'Netflix', 'Hulu', 'Prime Video', 'Disney+',
       'Type', 'Runtime'],
      dtype='object')
Categorical Columns: Index(['Title', 'Age', 'Rotten Tomatoes', 'Directors', 'Genres', 'Country',
       'Language'],
      dtype='object')

In [ ]:
for col in num_cols:
    df[col] = df[col].fillna(df[col].mean())

for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [ ]:
df.isnull().sum()

ID                 0
Title              0
Year               0
Age                0
IMDb               0
Rotten Tomatoes    0
Netflix            0
Hulu               0
Prime Video        0
Disney+            0
Type               0
Directors          0
Genres             0
Country            0
Language           0
Runtime            0
dtype: int64

In [ ]:
for col in num_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    df = df[(df[col] >= Q1 - 1.5 * IQR) & (df[col] <= Q3 + 1.5 * IQR)]

In [ ]:
df.info()
df.head(30)

<class 'pandas.core.frame.DataFrame'>
Index: 8466 entries, 4442 to 16211
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               8466 non-null   int64
 1   Title            8466 non-null   object
 2   Year             8466 non-null   int64
 3   Age              8466 non-null   object
 4   IMDb             8466 non-null   float64
 5   Rotten Tomatoes  8466 non-null   object
 6   Netflix          8466 non-null   float64
 7   Hulu             8466 non-null   int64
 8   Prime Video      8466 non-null   int64
 9   Disney+          8466 non-null   int64
 10  Type             8466 non-null   int64
 11  Directors        8466 non-null   object
 12  Genres           8466 non-null   object
 13  Country          8466 non-null   object
 14  Language         8466 non-null   object
 15  Runtime          8466 non-null   float64
dtypes: float64(3), int64(6), object(7)
memory usage: 1.1+ MB

,ID,Title,Year,Age,IMDb,Rotten Tomatoes,Netflix,Hulu,Prime Video,Disney+,Type,Directors,Genres,Country,Language,Runtime
4442,4443,Airplane!,1980,7+,7.7,97%,0.0,0,1,0,0,"Jim Abrahams,David Zucker,Jerry Zucker",Comedy,United States,English,88.0
4447,4448,Lady Bird,2017,18+,7.4,99%,0.0,0,1,0,0,Greta Gerwig,"Comedy,Drama",United States,"English,Spanish",94.0
4450,4451,The Big Sick,2017,18+,7.5,98%,0.0,0,1,0,0,Michael Showalter,"Comedy,Drama,Romance",United States,"English,Urdu",120.0
4452,4453,The Man from Nowhere,2010,18+,7.8,100%,0.0,0,1,0,0,Jeong-beom Lee,"Action,Drama,Thriller",South Korea,"Korean,English",119.0
4453,4454,Short Term 12,2013,18+,8.0,98%,0.0,0,1,0,0,Destin Daniel Cretton,Drama,United States,English,96.0
4457,4458,The Machinist,2004,18+,7.7,77%,0.0,0,1,0,0,Brad Anderson,"Drama,Thriller","Spain,France,United Kingdom,United States","English,Spanish",101.0
4459,4460,Dear Zachary: A Letter to a Son About His Father,2008,18+,8.6,94%,0.0,0,1,0,0,Kurt Kuenne,"Documentary,Biography,Crime,Drama",United States,English,95.0
4461,4462,The Disaster Artist,2017,18+,7.4,91%,0.0,0,1,0,0,James Franco,"Biography,Comedy,Drama",United States,English,104.0
4463,4464,Pi,1998,18+,7.4,88%,0.0,0,1,0,0,Darren Aronofsky,"Drama,Horror,Mystery,Sci-Fi,Thriller",United States,"English,Hebrew",84.0
4464,4465,The Lighthouse,2019,18+,7.6,90%,0.0,0,1,0,0,Robert Eggers,"Drama,Fantasy,Horror,Mystery","Canada,United States",English,109.0
4465,4466,The Farewell,2019,7+,7.6,98%,0.0,0,1,0,0,Lulu Wang,"Comedy,Drama","United States,China","Mandarin,English,Japanese,Italian",100.0
4473,4474,Stop Making Sense,1984,18+,8.6,100%,0.0,0,1,0,0,Jonathan Demme,"Documentary,Music",United States,English,88.0
4474,4475,Eighth Grade,2018,18+,7.4,99%,0.0,0,1,0,0,Bo Burnham,"Comedy,Drama",United States,English,93.0
4476,4477,Temple Grandin,2010,7+,8.3,100%,0.0,0,1,0,0,Mick Jackson,"Biography,Drama",United States,English,107.0
4477,4478,The Lincoln Lawyer,2011,18+,7.3,84%,0.0,0,1,0,0,Brad Furman,"Crime,Drama,Thriller",United States,English,118.0
4482,4483,Logan Lucky,2017,13+,7.0,92%,0.0,0,1,0,0,Steven Soderbergh,"Comedy,Crime,Drama","United States,China",English,118.0
4483,4484,The Act of Killing,2012,18+,8.2,95%,0.0,0,1,0,0,"Joshua Oppenheimer,Anonymous,Christine Cynn","Documentary,Biography,Crime,History","United Kingdom,Denmark,Norway","Indonesian,English",117.0
4484,4485,Leave No Trace,2018,7+,7.2,100%,0.0,0,1,0,0,Debra Granik,Drama,"United States,Canada",English,109.0
4487,4488,Escape from New York,1981,18+,7.2,86%,0.0,0,1,0,0,John Carpenter,"Action,Adventure,Sci-Fi",United States,English,99.0
4489,4490,Inside Llewyn Davis,2013,18+,7.5,92%,0.0,0,1,0,0,"Ethan Coen,Joel Coen","Comedy,Drama,Music","United States,United Kingdom,France",English,104.0
4492,4493,Pride,2014,18+,7.8,91%,0.0,0,1,0,0,Matthew Warchus,"Biography,Comedy,Drama,History,Romance","United Kingdom,France,United States","English,Welsh",119.0
4494,4495,Dead Man Walking,1995,18+,7.5,95%,0.0,0,1,0,0,Tim Robbins,"Crime,Drama","United Kingdom,United States",English,122.0
4495,4496,Grizzly Man,2005,18+,7.8,92%,0.0,0,1,0,0,Werner Herzog,"Documentary,Biography",United States,English,103.0
4496,4497,A Bittersweet Life,2005,18+,7.6,100%,0.0,0,1,0,0,Jee-woon Kim,"Action,Crime,Drama,Thriller",South Korea,"Korean,Russian",119.0
4497,4498,Tumbbad,2018,18+,8.3,89%,0.0,0,1,0,0,"Rahi Anil Barve,Anand Gandhi,Adesh Prasad","Drama,Fantasy,Horror,Thriller","India,Sweden",Hindi,104.0
4498,4499,A Man Called Ove,2015,13+,7.7,90%,0.0,0,1,0,0,Hannes Holm,"Comedy,Drama,Romance",Sweden,"Swedish,Persian",116.0
4499,4500,The Imposter,2012,18+,7.5,95%,0.0,0,1,0,0,Bart Layton,"Documentary,Biography,Crime,Drama,Thriller","United Kingdom,United States","English,Spanish",99.0
4500,4501,Capote,2005,18+,7.3,90%,0.0,0,1,0,0,Bennett Miller,"Biography,Crime,Drama,History","United States,Canada",English,114.0
4503,4504,The Salesman,2016,13+,7.8,96%,0.0,0,1,0,0,Asghar Farhadi,"Drama,Thriller","Iran,France","Persian,English",124.0
4504,4505,3-Iron,2004,18+,8.0,87%,0.0,0,1,0,0,Ki-duk Kim,"Crime,Drama,Romance","South Korea,Japan",Korean,88.0

In [ ]:
df.describe(include='all')

,ID,Title,Year,Age,IMDb,Rotten Tomatoes,Netflix,Hulu,Prime Video,Disney+,Type,Directors,Genres,Country,Language,Runtime
count,8466.000000,8466,8466.000000,8466,8466.000000,8466,8466.0,8466.0,8466.0,8466.0,8466.0,8466,8466,8466,8466,8466.000000
unique,NaN,8466,NaN,5,NaN,99,NaN,NaN,NaN,NaN,NaN,6695,1078,808,584,NaN
top,NaN,Beneath Alcatraz,NaN,18+,NaN,100%,NaN,NaN,NaN,NaN,NaN,Jay Chapman,Drama,United States,English,NaN
freq,NaN,1,NaN,6860,NaN,6389,NaN,NaN,NaN,NaN,NaN,323,1007,4968,6520,NaN
mean,10200.949090,NaN,2007.933144,NaN,5.689773,NaN,0.0,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,92.461203
std,3398.002652,NaN,10.341449,NaN,1.361597,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,12.999171
min,4443.000000,NaN,1976.000000,NaN,2.400000,NaN,0.0,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,59.000000
25%,7235.250000,NaN,2005.000000,NaN,4.700000,NaN,0.0,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,85.000000
50%,10081.500000,NaN,2012.000000,NaN,5.900000,NaN,0.0,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,92.000000
75%,13118.750000,NaN,2015.000000,NaN,6.700000,NaN,0.0,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,100.000000
max,16212.000000,NaN,2020.000000,NaN,9.300000,NaN,0.0,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,126.000000

In [ ]:
df.isnull().sum()

ID                 0
Title              0
Year               0
Age                0
IMDb               0
Rotten Tomatoes    0
Netflix            0
Hulu               0
Prime Video        0
Disney+            0
Type               0
Directors          0
Genres             0
Country            0
Language           0
Runtime            0
dtype: int64

In [ ]:
df.head(40)

,ID,Title,Year,Age,IMDb,Rotten Tomatoes,Netflix,Hulu,Prime Video,Disney+,Type,Directors,Genres,Country,Language,Runtime
4442,4443,Airplane!,1980,7+,7.7,97%,0.0,0,1,0,0,"Jim Abrahams,David Zucker,Jerry Zucker",Comedy,United States,English,88.0
4447,4448,Lady Bird,2017,18+,7.4,99%,0.0,0,1,0,0,Greta Gerwig,"Comedy,Drama",United States,"English,Spanish",94.0
4450,4451,The Big Sick,2017,18+,7.5,98%,0.0,0,1,0,0,Michael Showalter,"Comedy,Drama,Romance",United States,"English,Urdu",120.0
4452,4453,The Man from Nowhere,2010,18+,7.8,100%,0.0,0,1,0,0,Jeong-beom Lee,"Action,Drama,Thriller",South Korea,"Korean,English",119.0
4453,4454,Short Term 12,2013,18+,8.0,98%,0.0,0,1,0,0,Destin Daniel Cretton,Drama,United States,English,96.0
4457,4458,The Machinist,2004,18+,7.7,77%,0.0,0,1,0,0,Brad Anderson,"Drama,Thriller","Spain,France,United Kingdom,United States","English,Spanish",101.0
4459,4460,Dear Zachary: A Letter to a Son About His Father,2008,18+,8.6,94%,0.0,0,1,0,0,Kurt Kuenne,"Documentary,Biography,Crime,Drama",United States,English,95.0
4461,4462,The Disaster Artist,2017,18+,7.4,91%,0.0,0,1,0,0,James Franco,"Biography,Comedy,Drama",United States,English,104.0
4463,4464,Pi,1998,18+,7.4,88%,0.0,0,1,0,0,Darren Aronofsky,"Drama,Horror,Mystery,Sci-Fi,Thriller",United States,"English,Hebrew",84.0
4464,4465,The Lighthouse,2019,18+,7.6,90%,0.0,0,1,0,0,Robert Eggers,"Drama,Fantasy,Horror,Mystery","Canada,United States",English,109.0
4465,4466,The Farewell,2019,7+,7.6,98%,0.0,0,1,0,0,Lulu Wang,"Comedy,Drama","United States,China","Mandarin,English,Japanese,Italian",100.0
4473,4474,Stop Making Sense,1984,18+,8.6,100%,0.0,0,1,0,0,Jonathan Demme,"Documentary,Music",United States,English,88.0
4474,4475,Eighth Grade,2018,18+,7.4,99%,0.0,0,1,0,0,Bo Burnham,"Comedy,Drama",United States,English,93.0
4476,4477,Temple Grandin,2010,7+,8.3,100%,0.0,0,1,0,0,Mick Jackson,"Biography,Drama",United States,English,107.0
4477,4478,The Lincoln Lawyer,2011,18+,7.3,84%,0.0,0,1,0,0,Brad Furman,"Crime,Drama,Thriller",United States,English,118.0
4482,4483,Logan Lucky,2017,13+,7.0,92%,0.0,0,1,0,0,Steven Soderbergh,"Comedy,Crime,Drama","United States,China",English,118.0
4483,4484,The Act of Killing,2012,18+,8.2,95%,0.0,0,1,0,0,"Joshua Oppenheimer,Anonymous,Christine Cynn","Documentary,Biography,Crime,History","United Kingdom,Denmark,Norway","Indonesian,English",117.0
4484,4485,Leave No Trace,2018,7+,7.2,100%,0.0,0,1,0,0,Debra Granik,Drama,"United States,Canada",English,109.0
4487,4488,Escape from New York,1981,18+,7.2,86%,0.0,0,1,0,0,John Carpenter,"Action,Adventure,Sci-Fi",United States,English,99.0
4489,4490,Inside Llewyn Davis,2013,18+,7.5,92%,0.0,0,1,0,0,"Ethan Coen,Joel Coen","Comedy,Drama,Music","United States,United Kingdom,France",English,104.0
4492,4493,Pride,2014,18+,7.8,91%,0.0,0,1,0,0,Matthew Warchus,"Biography,Comedy,Drama,History,Romance","United Kingdom,France,United States","English,Welsh",119.0
4494,4495,Dead Man Walking,1995,18+,7.5,95%,0.0,0,1,0,0,Tim Robbins,"Crime,Drama","United Kingdom,United States",English,122.0
4495,4496,Grizzly Man,2005,18+,7.8,92%,0.0,0,1,0,0,Werner Herzog,"Documentary,Biography",United States,English,103.0
4496,4497,A Bittersweet Life,2005,18+,7.6,100%,0.0,0,1,0,0,Jee-woon Kim,"Action,Crime,Drama,Thriller",South Korea,"Korean,Russian",119.0
4497,4498,Tumbbad,2018,18+,8.3,89%,0.0,0,1,0,0,"Rahi Anil Barve,Anand Gandhi,Adesh Prasad","Drama,Fantasy,Horror,Thriller","India,Sweden",Hindi,104.0
4498,4499,A Man Called Ove,2015,13+,7.7,90%,0.0,0,1,0,0,Hannes Holm,"Comedy,Drama,Romance",Sweden,"Swedish,Persian",116.0
4499,4500,The Imposter,2012,18+,7.5,95%,0.0,0,1,0,0,Bart Layton,"Documentary,Biography,Crime,Drama,Thriller","United Kingdom,United States","English,Spanish",99.0
4500,4501,Capote,2005,18+,7.3,90%,0.0,0,1,0,0,Bennett Miller,"Biography,Crime,Drama,History","United States,Canada",English,114.0
4503,4504,The Salesman,2016,13+,7.8,96%,0.0,0,1,0,0,Asghar Farhadi,"Drama,Thriller","Iran,France","Persian,English",124.0
4504,4505,3-Iron,2004,18+,8.0,87%,0.0,0,1,0,0,Ki-duk Kim,"Crime,Drama,Romance","South Korea,Japan",Korean,88.0
4507,4508,Samsara,2011,13+,8.5,76%,0.0,0,1,0,0,Ron Fricke,"Documentary,Music","United States,Indonesia,Singapore,Thailand,Ken...",English,102.0
4509,4510,The Hours,2002,13+,7.5,80%,0.0,0,1,0,0,Stephen Daldry,"Drama,Romance","United States,United Kingdom,France,Canada,Ger...",English,110.0
4510,4511,Seven Psychopaths,2012,18+,7.2,82%,0.0,0,1,0,0,Martin McDonagh,"Comedy,Crime","United Kingdom,United States","English,Vietnamese",110.0
4511,4512,For Sama,2019,7+,8.5,99%,0.0,0,1,0,0,"Waad Al-Kateab,Edward Watts","Documentary,War","United Kingdom,Syria,United States","Arabic,English",100.0
4513,4514,Bridget Jones's Diary,2001,18+,6.7,80%,0.0,0,1,0,0,Sharon Maguire,"Comedy,Drama,Romance","United Kingdom,France,United States",English,97.0
4514,4515,The Last Waltz,1978,7+,8.2,98%,0.0,0,1,0,0,Martin Scorsese,"Documentary,Biography,Music",United States,"English,Middle English",117.0
4515,4516,Lars and the Real Girl,2007,13+,7.3,81%,0.0,0,1,0,0,Craig Gillespie,"Comedy,Drama,Romance","United States,Canada","English,Spanish",106.0
4516,4517,The Look of Silence,2014,13+,8.3,96%,0.0,0,1,0,0,Joshua Oppenheimer,"Documentary,Biography,History","Denmark,Indonesia,Finland,Norway,United Kingdo...",Indonesian,103.0
4517,4518,Cold War,2018,18+,7.6,93%,0.0,0,1,0,0,Pawel Pawlikowski,"Drama,History,Music,Romance","Poland,United Kingdom,France","Polish,French,Croatian,German,Russian,Serbian,...",89.0
4519,4520,Honey Boy,2019,18+,7.3,94%,0.0,0,1,0,0,Alma Har'el,Drama,United States,"English,Spanish",94.0

In [ ]:
df.to_csv("MoviesOnStreamingPlatforms_updated_cleaned.csv", index=False)

In [ ]:
df.to_csv("MoviesOnStreamingPlatforms_updated_cleaned.csv")
from google.colab import files
files.download("MoviesOnStreamingPlatforms_updated_cleaned.csv")